### ISSUE TITLE
Final circle(s) in 'no man's land' - DayZ BR (ArmA 2) 0.9.6.3

### ISSUE THREAD

**Issue by VeritechHT1** [BattleRoyaleGames/ArmA3-BattleRoyale-Issues#15]
I'm not sure if this is the most appropriate forum, but since a mod on the community forum stated to post bugs here at the ArmA 3 GitHub for DayZ BR (A2) bugs I'll post it here (relevant post: http://dayzbattleroyale.com/community/discussion/27/-9-6-3-critiques#Item_3).

In a recent match on 12 May 2014 on UK 1 hosted by gamingdeluxe.co.uk from 10:08AM EST (GMT-5) to 11:05AM EST (GMT-5) the final circle(s) were placed on 'no man's land.'

http://imgur.com/a/KBH1V

The above image gallery shows circles one, two, three and four: I was killed right after the drawing of circle four but since that entire circle was in 'no man's land' any successive circles would have been drawn in that space as well, assuming that there wasn't any deviations from script.

It should be noted that the successive circles also shift in one direction primarily: I.e. downward or to the South. Obviously it would be to someones benefit for that to happen if they were already located in that space as no one would suspect that they were there nor go look for them in that location. And I have video capture with all player names if relevant.

**Comment by lazyink** [comment]
That can sometimes happen due to the randomness of the circle. I will look into pushing a fix for this once I get situated back in Ireland in a few weeks. 

Also, for now, please report the Arma 2 issues on the DayZ Battle Royale server issue tracker located here: https://github.com/BattleRoyaleGames/ArmA2-DayZBattleRoyale-Server/issues
