### ISSUE TITLE
No backpacks spawning at beginning of round - DayZ BR (ArmA 2) 0.9.6.3

### ISSUE THREAD

**Issue by VeritechHT1** [BattleRoyaleGames/ArmA3-BattleRoyale-Issues#16]
At the beginning of a DayZ BR (ArmA 2) 0.9.6.3 round there were no backpacks in the starting point. The issue did not seem to be one of desync as none of the players have any desync, as noted when I scroll through the player list; in addition you can hear via in-game communications other players comment on 'where are the backpacks?' so therefore it is not an issue with my client alone.

http://youtu.be/lNdLgM65Mbo

The server was UK 3, hosted by gamingdeluxe.co.uk, the date was 13 May 2014 and the playtime was from 1:39PM EST (GMT-5) to 2:37PM EST (GMT-5).

Note, that without backpacks players have no access to maps that I am aware of as maps, nor GPS, spawn in the game environment. Therefore if someone is either trolling the entire player set, or advantaging themselves as they have some form of ESP, then players are at a serious disadvantage for direction, location of bombing zones and most importantly, the location of the blue circle(s).

**Comment by lazyink** [comment]
Not sure why that happened to be honest. May have just been a glitch with the server. Since it is not a comment occurance, it will be very hard to track down unless you can replicate it. 

Again, please report all the issues with the Arma 2 version over on the DayZ Battle Royale server issue tracker! Thanks.

https://github.com/BattleRoyaleGames/ArmA2-DayZBattleRoyale-Server/issues
